<a href="https://colab.research.google.com/github/PigeonLore/PigeonLore/blob/main/Bakery_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bake Sale Mini-Project**

**Our Task**

Often in your work as a data science you will be loading outside datasets into your Python environment. Today, however, we will create a simple data set for a mini-project analyzing the results of a bake sale.


Let's suppose the "Teens for Tech" club has asked you to help them analyze data from their ongoing bake sale.




* They are planning on selling the following baked goods every day for a week.em

  1.   brownie: $2

  2.   cookie: $1

  3.   cake: $10

* They were hoping to raise $200.



# 1. Starting with Lists
**Names**

* Declare a variable, ` name_list `, that is a list containing the names of the baked goods they plan to sell.
* Print the names list

In [36]:
names_list = ['brownie','cookie','cake']
print(names_list)

['brownie', 'cookie', 'cake']


# Prices
* Declare a second variable, `prices_list`, that is a list containing the prices of each good (as integers).
  * Make that you have the names and prices in the same order (if brownie is first in your names list, then its price should be the first value in your prices list).
* Print the prices list.

In [37]:
prices_list = [2,1,10]
print(prices_list)

[2, 1, 10]


# Bake Sale Results (So Far)
**Quantities Sold**
* So far, the club has sold:
  * 17 brownies
  * 40 cookies
  * and 1 cake.
* Declare a new list with these values called `quantities_sold_list`.
* Print the quantities_sold_list.

In [38]:
quantities_sold_list = [17,40,1]
print(quantities_sold_list)

[17, 40, 1]


# Calculating the Sales
You should now have:

  * a list called `names_list` that contains 'brownie', 'cookie', 'cake'
  * a list called `prices_list` that contains 2,1,10.
  * a list called `quantities_sold_list` that contains 17, 40, 1.
  
We want to calculate the total money earned from each of the baked goods so far. We simply need to multiply each price by the corresponding quantity sold.

In [39]:
# prices_list * quantities_sold_list

# 2. Creating a NumPy Array
First, we must import NumPy. We will use the conventional alias, np. Once you've done that NumPy will be loaded and you can start start using its functions.

In [40]:
import numpy as np

# Converting Our Lists to 1-Dimensional Arrays
You can use the function `np.array()` to change a Python collection into a NumPy array.

* Create new NumPy array versions of the `prices_list`, `quantities_sold_list`, and `names_list`.
  * We can drop the `_list` from the names of our new variables.
* Print each of them.

The result should look like a list with no commas. (Remember you could use display() instead of print() if you prefer to see the commas separating each value.)

In [41]:
from numpy.matrixlib.defmatrix import N
# convert each of our lists to a numpy array and print it to verify the result
names = N.array(names_list)
print(names)
prices = N.array(prices_list)
print(prices)
quantities_sold = N.array(quantities_sold_list)
print(quantities_sold)

['brownie' 'cookie' 'cake']
[ 2  1 10]
[17 40  1]


Arrays are ordered and mutable, just like lists, but they are faster and more memory efficient.

 # 3. Elementwise Calculations

**Calculating Our Sales (For real this time!)**

Unlike lists, arrays can be multiplied. Now, let's go back to our original problem: we would like to find the money collected for each type of item. We want the price * quantity_sold for each item. Let's try multiplying our arrays.

In [42]:
prices * quantities_sold

array([34, 40, 10])

Yes! by using the NumPy arrays, we can easily determine that we collected 
\$34  from the sale of brownies, 
\$40 from the sale of cookies,
and
\$10 for the sale of cakes. 

As you saw above, we calculated the revenue for each baked good so far, the multiplication was applied between the first element of each array, then between the second element of each array, and so on. This is known as an 

*"elementwise" calculation.*

Let's look at another example of elementwise calculations by factoring in the cost to make each baked good.

# Accounting for Costs
The club wants to account for the expense of making each baked good so that we can calculate the profit for each baked good (Profit = price - expenses).

The expense of making each baked good is:

* a brownie costs $0.25 to make.

* a cookie costs $0.50 to make.

* a cake costs $5.00 to make.

Now, let's create an array that corresponds to the expense of making each of the items sold at the bake sale.

In [43]:
expenses_list = [0.25,0.5,5.00]
expenses = np.array(expenses_list)
print(expenses)

[0.25 0.5  5.  ]


* Note: alternately, we could do this in 1 step by creating our list inside of np.array() instead of saving it as a separate variable first.

In [44]:
expenses = N.array([0.25,0.5,5.00])
print(expenses)

[0.25 0.5  5.  ]


# Calculating Profits
  * To find the profit of each baked good, we want to subtract the expenses from the price.

In [45]:
profits = prices - expenses
profits

array([1.75, 0.5 , 5.  ])

# Elementwise Booleans
Suppose you wanted to identify which items made a profit greater than $2 per item. You could use the following code to ask if the statement is true or false for each element in the array.

In [46]:
profits > 2

array([False, False,  True])

But what if we wanted to know the **names** of which baked goods had profits > 2.

  * We could save the True/False array above and then use that as an index to slice from our array of names!

In [47]:
index_profits = profits > 2
index_profits

array([False, False,  True])

In [48]:
names[index_profits]

array(['cake'], dtype='<U7')

* NumPy automatically assumed that we only wanted the values from names where the index was True.

* If we wanted to get the opposite list of names with profits <=2, we could create a new index of `profits <=2`.

* But since we already have the opposite list, we can simply use the `~` operator to take the opposite result.

In [49]:
~index_profits

array([ True,  True, False])

In [50]:
names[~index_profits]

array(['brownie', 'cookie'], dtype='<U7')

# 4. Appending, Deleting, and Replacing Elements in a NumPy Array

**Appending**

The club will also sell pies for $7 so we need to update our price_array.

Based on your experience with lists, you might think the following code would work to include an additional element to our array:

In [51]:
prices = prices + [7]
prices

array([ 9,  8, 17])

Wait! This is **not** the output we wanted! The NumPy array did what it does best: it added seven to each element in the array.

To get back to the original values, we will subtract 7, then use the np.append() function to include the value 7 to the end of our array as desired.

In [52]:
prices = prices - [7]
prices

array([ 2,  1, 10])

* Appending names of new baked good in names array.

In [53]:
prices = np.append(prices, 7)
prices

array([ 2,  1, 10,  7])

In [54]:
names = np.append(names, 'pie')
names

array(['brownie', 'cookie', 'cake', 'pie'], dtype='<U7')

**Appending Multiple Elements at Once**
You can also append multiple values to the array in one command.

For example, the club want to add the following items and prices:

* \$4.50 for fudge.
* \$3 for a cupcake.
* \$4 for a loaf of banana bread.
* \$9 for a torte.

Notice the use of the square brackets to create a list as the second argument in the following code. This will append all four values to the array at once:

In [55]:
prices = np.append(prices, [4.50, 3, 4, 9])
prices

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ,  9. ])

* Now let's append the new baked good's names to our names array.

In [56]:
names = np.append(names, ['fudge','cupcake','banana bread','torte'])
names

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread', 'torte'], dtype='<U12')

**Deleting**

It turns out nobody plans to make a torte, so they want to remove the price of that item from the prices array and its name from the names array.

We will use the np.delete() command, but we need to indicate which element to delete.

We use indexing (much the same as indexing for lists) to indicate we want to remove the element at index 7 (remember to use zero-indexing) or since it is the last element, we could go from the right and use negative indexing (-1).

In [57]:
names = np.delete(names, -1)
display(names)
prices = np.delete(prices, -1)
prices

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread'], dtype='<U12')

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ])

**Replacing**

The club decided to raise the price of cakes from \$10 to \$12. We need to reflect this in our prices array.

Once again, we will need to identify the element using the index. Let's confirm which index corresponds to cake. One approach we can use is the `enumerate` function.

In [58]:
prices[2] = 12
print(names[2])
prices[2]

cake


12.0

# Assingment Starts Here
--------------------------------------------------------------------------------

# 1) Use the enumerate function to print out the index # and name of every baked good in your `names` array.

In [59]:
for i, name in enumerate(names):
  print(f'Index {i}: {name}')

Index 0: brownie
Index 1: cookie
Index 2: cake
Index 3: pie
Index 4: fudge
Index 5: cupcake
Index 6: banana bread


 # 2. Update the quantity_sold_array to include the sale of 2 pies, 3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread. You also realize that one of the cookies you thought was sold had actually fallen on the ground, so edit the quantity_sold_array from 40 to 39.

In [60]:
#print(names[:7])
#print(quantities_sold[:])
quantities_sold = np.append(quantities_sold, [2,3,16,5])
#print(quantities_sold)

In [61]:
quantities_sold[1] = 39
quantities_sold
#np.sum(quantities_sold)

array([17, 39,  1,  2,  3, 16,  5])

# 3) Determine the amount of money collected from the sale of each item at the bake sale.

In [62]:
total_money = quantities_sold * prices
#print(total_money)
print(f"${np.sum(total_money)}")

$180.5


# 4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread. 
**Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?**

In [63]:
quantities_leftover = np.array([0,0,2,1,6,0,2])
quantities_leftover

array([0, 0, 2, 1, 6, 0, 2])

# 5) The club decides to sell the leftover items at half price and everything quickly sells out! Determine how much money was collected from the clearance sale.

In [64]:
prices_clearance = prices / 2
#print(prices_clearance)
total_money_clearance =  np.sum(prices_clearance)
total_sold = quantities_leftover * prices_clearance
#print(total_money)
#print(total_sold)
#print(prices)

# 6) How much total money was collected from the bake sale (including the sale of full price and clearance items)? Hint: Your final answer should be $213.50, but you must make sure you get this answer with your NumPy coding skills!!

In [65]:
print(f'${np.sum(total_money) + np.sum(total_sold)}')

$213.5
